/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LayoutDefault: typeof import('./components/layouts/LayoutDefault.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIButton: typeof import('./components/ui/UIButton.vue')['default']
    UIScrollTop: typeof import('./components/ui/UIScrollTop.vue')['default']
  }
}
